<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $projects = [
            [
                'name' => 'Manufacturing Equipment Upgrade',
                'description' => 'Complete overhaul of production line equipment for improved efficiency',
                'sector' => 'EMR_MFG',
                'status' => 'active',
                'start_date' => Carbon::now()->subDays(45),
                'end_date' => Carbon::now()->addDays(90),
                'client_name' => 'ABC Manufacturing Ltd',
                'client_contact' => 'john.doe@abcmfg.com',
                'pipeline_stage' => 'execution',
                'pipeline_intake_date' => Carbon::now()->subDays(60),
                'oem' => 'Siemens',
                'location' => 'Lagos, Nigeria',
                'expected_close_date' => Carbon::now()->addDays(90),
                'business_segment' => 'EMR_MFG',
                'product' => 'Industrial Automation',
                'sub_product' => 'PLC Systems',
                'channel_partner' => 'Tech Solutions Nigeria',
                'contract_value_ngn' => 12500000,
                'contract_value_usd' => 7812.50,
                'margin_percent_ngn' => 25,
                'margin_percent_usd' => 25,
                'margin_value_ngn' => 3125000,
                'margin_value_usd' => 1953.13,
                'deal_probability' => 'high',
                'progress' => 65,
            ],
            [
                'name' => 'Oil & Gas Pipeline Inspection',
                'description' => 'Comprehensive pipeline integrity assessment and monitoring system',
                'sector' => 'EMR_OGP',
                'status' => 'active',
                'start_date' => Carbon::now()->subDays(30),
                'end_date' => Carbon::now()->addDays(120),
                'client_name' => 'Nigerian Petroleum Corp',
                'client_contact' => 'sarah.jones@npc.ng',
                'pipeline_stage' => 'negotiation',
                'pipeline_intake_date' => Carbon::now()->subDays(50),
                'oem' => 'Baker Hughes',
                'location' => 'Port Harcourt, Nigeria',
                'expected_close_date' => Carbon::now()->addDays(60),
                'business_segment' => 'EMR_OGP',
                'product' => 'Pipeline Monitoring',
                'sub_product' => 'Smart Sensors',
                'channel_partner' => 'Energy Tech Partners',
                'contract_value_ngn' => 45000000,
                'contract_value_usd' => 28125,
                'margin_percent_ngn' => 30,
                'margin_percent_usd' => 30,
                'margin_value_ngn' => 13500000,
                'margin_value_usd' => 8437.50,
                'deal_probability' => 'high',
                'progress' => 45,
            ],
            [
                'name' => 'Healthcare IT Infrastructure',
                'description' => 'Hospital management system deployment and training',
                'sector' => 'EMR_Healthcare',
                'status' => 'active',
                'start_date' => Carbon::now()->subDays(15),
                'end_date' => Carbon::now()->addDays(150),
                'client_name' => 'General Hospital Lagos',
                'client_contact' => 'dr.williams@ghl.ng',
                'pipeline_stage' => 'proposal',
                'pipeline_intake_date' => Carbon::now()->subDays(25),
                'oem' => 'Epic Systems',
                'location' => 'Lagos, Nigeria',
                'expected_close_date' => Carbon::now()->addDays(45),
                'business_segment' => 'EMR_Healthcare',
                'product' => 'Hospital Management System',
                'sub_product' => 'EMR Software',
                'channel_partner' => 'HealthTech Solutions',
                'contract_value_ngn' => 8750000,
                'contract_value_usd' => 5468.75,
                'margin_percent_ngn' => 35,
                'margin_percent_usd' => 35,
                'margin_value_ngn' => 3062500,
                'margin_value_usd' => 1914.06,
                'deal_probability' => 'medium',
                'progress' => 25,
            ],
            [
                'name' => 'Renewable Energy Installation',
                'description' => 'Solar panel installation for commercial building',
                'sector' => 'EMR_Renewables',
                'status' => 'active',
                'start_date' => Carbon::now()->subDays(10),
                'end_date' => Carbon::now()->addDays(60),
                'client_name' => 'Green Energy Ltd',
                'client_contact' => 'mike.brown@greenenergy.ng',
                'pipeline_stage' => 'qualification',
                'pipeline_intake_date' => Carbon::now()->subDays(20),
                'oem' => 'SunPower',
                'location' => 'Abuja, Nigeria',
                'expected_close_date' => Carbon::now()->addDays(30),
                'business_segment' => 'EMR_Renewables',
                'product' => 'Solar Panels',
                'sub_product' => '500kW System',
                'channel_partner' => 'Solar Solutions Africa',
                'contract_value_ngn' => 16000000,
                'contract_value_usd' => 10000,
                'margin_percent_ngn' => 28,
                'margin_percent_usd' => 28,
                'margin_value_ngn' => 4480000,
                'margin_value_usd' => 2800,
                'deal_probability' => 'medium',
                'progress' => 15,
            ],
            [
                'name' => 'Corporate IT Services Contract',
                'description' => 'Managed IT services and support for enterprise',
                'sector' => 'EMR_Services',
                'status' => 'active',
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(365),
                'client_name' => 'First Bank of Nigeria',
                'client_contact' => 'tech@firstbank.ng',
                'pipeline_stage' => 'initiation',
                'pipeline_intake_date' => Carbon::now()->subDays(5),
                'oem' => 'Microsoft',
                'location' => 'Lagos, Nigeria',
                'expected_close_date' => Carbon::now()->addDays(90),
                'business_segment' => 'EMR_Services',
                'product' => 'Managed Services',
                'sub_product' => 'IT Support & Maintenance',
                'channel_partner' => 'IT Services Nigeria',
                'contract_value_ngn' => 24000000,
                'contract_value_usd' => 15000,
                'margin_percent_ngn' => 40,
                'margin_percent_usd' => 40,
                'margin_value_ngn' => 9600000,
                'margin_value_usd' => 6000,
                'deal_probability' => 'low',
                'progress' => 5,
            ],
            [
                'name' => 'Trading Platform Development',
                'description' => 'Custom commodity trading platform with real-time analytics',
                'sector' => 'EMR_Trading',
                'status' => 'on-hold',
                'start_date' => Carbon::now()->subDays(20),
                'end_date' => null,
                'client_name' => 'Commodity Exchange Ltd',
                'client_contact' => 'operations@commodex.ng',
                'pipeline_stage' => 'proposal',
                'pipeline_intake_date' => Carbon::now()->subDays(40),
                'oem' => 'Oracle',
                'location' => 'Lagos, Nigeria',
                'expected_close_date' => null,
                'business_segment' => 'EMR_Trading',
                'product' => 'Trading Software',
                'sub_product' => 'Custom Platform',
                'channel_partner' => 'FinTech Partners',
                'contract_value_ngn' => 32000000,
                'contract_value_usd' => 20000,
                'margin_percent_ngn' => 45,
                'margin_percent_usd' => 45,
                'margin_value_ngn' => 14400000,
                'margin_value_usd' => 9000,
                'deal_probability' => 'uncertain',
                'progress' => 10,
            ],
            [
                'name' => 'Business Development Services',
                'description' => 'Comprehensive business consulting and advisory services',
                'sector' => 'BEDS_Services',
                'status' => 'completed',
                'start_date' => Carbon::now()->subDays(120),
                'end_date' => Carbon::now()->subDays(10),
                'client_name' => 'Startup Hub Nigeria',
                'client_contact' => 'ceo@startuphub.ng',
                'pipeline_stage' => 'closure',
                'pipeline_intake_date' => Carbon::now()->subDays(150),
                'oem' => null,
                'location' => 'Lagos, Nigeria',
                'expected_close_date' => Carbon::now()->subDays(10),
                'business_segment' => 'BEDS_Services',
                'product' => 'Consulting Services',
                'sub_product' => 'Strategy & Planning',
                'channel_partner' => null,
                'contract_value_ngn' => 6400000,
                'contract_value_usd' => 4000,
                'margin_percent_ngn' => 50,
                'margin_percent_usd' => 50,
                'margin_value_ngn' => 3200000,
                'margin_value_usd' => 2000,
                'deal_probability' => 'high',
                'progress' => 100,
            ],
        ];

        foreach ($projects as $projectData) {
            Project::create($projectData);
        }

        $this->command->info('Successfully seeded ' . count($projects) . ' projects!');
    }
}
