import api from './api';
import { Task, TaskStatus, TaskPriority, PipelineStage, ProjectDocument, DocumentType } from '@/types';
import { notifyAssignment } from './notificationHelper';

export interface CreateTaskData {
  title: string;
  description?: string;
  status?: TaskStatus;
  priority?: TaskPriority;
  assigneeId?: string;
  assigneeIds?: string[];
  requiresChairmanIntervention?: boolean;
  assignedToChairman?: boolean;
  dueDate?: string;
  projectId: string;
  notes?: string;
}

export interface UpdateTaskData extends Partial<CreateTaskData> {
  isAutoGenerated?: boolean;
  stageTriggered?: PipelineStage;
}

export interface TaskFilters {
  projectId?: string;
  status?: TaskStatus;
  priority?: TaskPriority;
  assigneeId?: string;
  requiresChairmanIntervention?: boolean;
  assignedToChairman?: boolean;
}

// Helper to normalize array responses from backend
const normalizeArray = (data: any): any[] => {
  if (Array.isArray(data)) return data;
  if (data && Array.isArray(data.data)) return data.data;
  return [];
};

// Convert frontend status format (kebab-case) to backend format (snake_case)
const statusToBackend = (status: TaskStatus): string => {
  const statusMap: Record<TaskStatus, string> = {
    'todo': 'todo',
    'in-progress': 'in_progress',
    'review': 'in_review',
    'completed': 'completed'
  };
  return statusMap[status] || status;
};

// Convert backend status format (snake_case) to frontend format (kebab-case)
const statusToFrontend = (status: string): TaskStatus => {
  const statusMap: Record<string, TaskStatus> = {
    'todo': 'todo',
    'in_progress': 'in-progress',
    'in_review': 'review',
    'completed': 'completed'
  };
  return (statusMap[status] || status) as TaskStatus;
};

const normalizeDocuments = (raw: unknown): ProjectDocument[] => {
  if (!raw || !Array.isArray(raw)) return [];
  return raw.map((d: Record<string, unknown>) => ({
    id: String(d.id ?? ''),
    name: String(d.name ?? 'file'),
    type: ((d.type as DocumentType) || 'supporting') as DocumentType,
    url: String(d.url ?? d.file_url ?? '#'),
    uploadedAt: String(d.uploaded_at ?? d.uploadedAt ?? new Date().toISOString()),
    uploadedBy: String(d.uploaded_by ?? d.uploadedBy ?? ''),
    size: Number(d.size) || 0,
    source: d.source === 'onedrive' ? 'onedrive' : 'local',
  }));
};

// Normalize a single task from backend format to frontend format
const normalizeTask = (task: any): Task => {
  const assigneesRaw = task.assignees ?? task.assigneeUsers ?? [];
  const assigneeIdsFromList = Array.isArray(assigneesRaw)
    ? assigneesRaw.map((a: any) => String(a.id ?? a.user_id ?? a)).filter(Boolean)
    : [];
  const assigneeIdsRaw = task.assigneeIds ?? task.assignee_ids ?? assigneeIdsFromList;
  const assigneeIds = (Array.isArray(assigneeIdsRaw) ? assigneeIdsRaw : [])
    .map((id: any) => String(id))
    .filter(Boolean);
  const primaryAssigneeId = task.assignee_id || task.assigneeId || assigneeIds[0];
  if (primaryAssigneeId && !assigneeIds.includes(String(primaryAssigneeId))) {
    assigneeIds.unshift(String(primaryAssigneeId));
  }

  const nestedAssignee = task.assignee;
  const assigneeLabel =
    typeof nestedAssignee === 'string'
      ? nestedAssignee
      : nestedAssignee?.name ||
        (Array.isArray(assigneesRaw)
          ? assigneesRaw.map((a: any) => a.name).filter(Boolean).join(', ')
          : undefined);

  return {
    ...task,
    id: String(task.id),
    status: statusToFrontend(task.status),
    projectId: String(task.project_id || task.projectId),
    assigneeId: primaryAssigneeId != null && primaryAssigneeId !== '' ? String(primaryAssigneeId) : undefined,
    assigneeIds,
    assignee: assigneeLabel,
    assignees: Array.isArray(assigneesRaw)
      ? assigneesRaw.map((a: any) => ({
          id: String(a.id ?? a.user_id ?? ''),
          name: a.name,
          email: a.email,
        }))
      : undefined,
    requiresChairmanIntervention: Boolean(
      task.requiresChairmanIntervention ?? task.requires_chairman_intervention
    ),
    assignedToChairman: Boolean(
      task.assignedToChairman ?? task.assigned_to_chairman
    ),
    dueDate: task.due_date || task.dueDate,
    createdAt: task.created_at || task.createdAt,
    stageTriggered: task.stage_triggered || task.stageTriggered,
    documents: normalizeDocuments(task.documents ?? task.attachments),
  };
};

// Normalize task array
const normalizeTasks = (tasks: any[]): Task[] => {
  return tasks.map(normalizeTask);
};

export const tasksService = {
  // Get all tasks (optionally filtered by project) — full dump escape hatch
  getAll: async (filters?: TaskFilters): Promise<Task[]> => {
    const params: Record<string, unknown> = {};
    if (filters?.projectId) params.project_id = filters.projectId;
    if (filters?.status) params.status = statusToBackend(filters.status);
    if (filters?.priority) params.priority = filters.priority;
    if (filters?.assigneeId) params.assignee_id = filters.assigneeId;
    if (filters?.requiresChairmanIntervention) {
      params.requires_chairman_intervention = 1;
    }
    if (filters?.assignedToChairman) {
      params.assigned_to_chairman = 1;
    }
    const response = await api.get('/api/tasks', {
      params: { ...params, all: 1 },
    });
    const tasks = normalizeArray(response.data);
    return normalizeTasks(tasks);
  },

  /** Server-paginated task list for All Tasks. */
  list: async (
    filters?: TaskFilters & { page?: number; per_page?: number; search?: string }
  ): Promise<{ tasks: Task[]; total: number; page: number; lastPage: number }> => {
    const params: Record<string, unknown> = {
      page: filters?.page ?? 1,
      per_page: filters?.per_page ?? 50,
    };
    if (filters?.projectId) params.project_id = filters.projectId;
    if (filters?.status) params.status = statusToBackend(filters.status);
    if (filters?.priority) params.priority = filters.priority;
    if (filters?.assigneeId) params.assignee_id = filters.assigneeId;
    if (filters?.search) params.search = filters.search;
    if (filters?.requiresChairmanIntervention) {
      params.requires_chairman_intervention = 1;
    }
    if (filters?.assignedToChairman) {
      params.assigned_to_chairman = 1;
    }
    const response = await api.get('/api/tasks', { params });
    const body = response.data ?? {};
    const tasks = normalizeTasks(normalizeArray(body));
    const meta = body.meta ?? {};
    return {
      tasks,
      total: Number(meta.total ?? tasks.length),
      page: Number(meta.current_page ?? params.page),
      lastPage: Number(meta.last_page ?? 1),
    };
  },

  // Get tasks for a specific project
  getByProject: async (projectId: string): Promise<Task[]> => {
    const response = await api.get(`/api/projects/${projectId}/tasks`);
    const tasks = normalizeArray(response.data);
    return normalizeTasks(tasks);
  },

  // Get single task by ID
  getById: async (id: string): Promise<Task> => {
    const response = await api.get(`/api/tasks/${id}`);
    return normalizeTask(response.data);
  },

  // Create new task
  create: async (data: CreateTaskData): Promise<Task> => {
    const ids = (data.assigneeIds ?? (data.assigneeId ? [data.assigneeId] : []))
      .map(String)
      .filter(Boolean);
    const backendData = {
      ...data,
      status: data.status ? statusToBackend(data.status) : undefined,
      assigneeIds: ids,
      assignee_ids: ids.map((id) => Number(id)).filter((n) => Number.isFinite(n) && n > 0),
      assigneeId: ids[0],
      assignee_id: ids[0] ? Number(ids[0]) : null,
    };
    const response = await api.post('/api/tasks', backendData);
    const createdTask = normalizeTask(response.data);
    
    // Send notification if task is assigned to someone
    if (createdTask.assigneeId) {
      await notifyAssignment({
        type: 'task_assigned',
        userId: createdTask.assigneeId,
        taskId: createdTask.id,
        taskTitle: createdTask.title,
        projectId: createdTask.projectId,
        projectName: 'Project', // Will be fetched if needed
        dueDate: createdTask.dueDate,
        message: `You have been assigned to task "${createdTask.title}"`,
      });
    }
    
    return createdTask;
  },

  // Update task
  update: async (id: string, data: UpdateTaskData, originalTask?: Task): Promise<Task> => {
    const hasAssigneeIds = Array.isArray(data.assigneeIds);
    const ids = hasAssigneeIds
      ? data.assigneeIds!.map(String).filter(Boolean)
      : data.assigneeId
        ? [String(data.assigneeId)]
        : undefined;

    const backendData: Record<string, unknown> = {
      ...data,
      status: data.status ? statusToBackend(data.status) : undefined,
    };
    if (ids) {
      backendData.assigneeIds = ids;
      backendData.assignee_ids = ids.map((i) => Number(i)).filter((n) => Number.isFinite(n) && n > 0);
      backendData.assigneeId = ids[0] ?? null;
      backendData.assignee_id = ids[0] ? Number(ids[0]) : null;
    }

    const response = await api.put(`/api/tasks/${id}`, backendData);
    const updatedTask = normalizeTask(response.data);
    
    // Send notification if assignee changed
    if (data.assigneeId && data.assigneeId !== originalTask?.assigneeId) {
      await notifyAssignment({
        type: 'task_assigned',
        userId: data.assigneeId,
        taskId: id,
        taskTitle: data.title || originalTask?.title || 'Untitled Task',
        projectId: originalTask?.projectId || '',
        projectName: 'Project', // Will be fetched if needed
        dueDate: data.dueDate || originalTask?.dueDate,
        message: `You have been assigned to task "${data.title || originalTask?.title || 'Untitled Task'}"`,
      });
    }
    
    return updatedTask;
  },

  // Update task status only
  updateStatus: async (id: string, status: TaskStatus): Promise<Task> => {
    // Convert status to backend format
    const backendStatus = statusToBackend(status);
    const response = await api.patch(`/api/tasks/${id}/status`, { status: backendStatus });
    return normalizeTask(response.data);
  },

  // Delete task
  delete: async (id: string): Promise<void> => {
    await api.delete(`/api/tasks/${id}`);
  },

  // Assign task to user
  assign: async (id: string, assigneeId: string, originalTask?: Task): Promise<Task> => {
    const response = await api.patch(`/api/tasks/${id}/assign`, { assigneeId });
    const assignedTask = normalizeTask(response.data);
    
    // Send notification
    if (assigneeId && assigneeId !== originalTask?.assigneeId) {
      await notifyAssignment({
        type: 'task_assigned',
        userId: assigneeId,
        taskId: id,
        taskTitle: assignedTask.title,
        projectId: assignedTask.projectId,
        projectName: 'Project',
        dueDate: assignedTask.dueDate,
        message: `You have been assigned to task "${assignedTask.title}"`,
      });
    }
    
    return assignedTask;
  },

  /** Upload one or more files; backend should return updated task with documents. */
  uploadAttachments: async (taskId: string, files: File[]): Promise<Task> => {
    const form = new FormData();
    files.forEach((f) => form.append('files[]', f));
    const response = await api.post(`/api/tasks/${taskId}/attachments`, form, {
      headers: { 'Content-Type': 'multipart/form-data' },
    });
    const body = response.data?.data ?? response.data?.task ?? response.data;
    return normalizeTask(body);
  },

  deleteAttachment: async (taskId: string, documentId: string): Promise<void> => {
    await api.delete(`/api/tasks/${taskId}/attachments/${documentId}`);
  },
};
