import api from './api';
import { Task, TaskStatus, TaskPriority, PipelineStage } from '@/types';
import { notifyAssignment } from './notificationHelper';

export interface CreateTaskData {
  title: string;
  description?: string;
  status?: TaskStatus;
  priority?: TaskPriority;
  assigneeId?: string;
  dueDate?: string;
  projectId: string;
  notes?: string;
}

export interface UpdateTaskData extends Partial<CreateTaskData> {
  isAutoGenerated?: boolean;
  stageTriggered?: PipelineStage;
}

export interface TaskFilters {
  projectId?: string;
  status?: TaskStatus;
  priority?: TaskPriority;
  assigneeId?: string;
}

// Helper to normalize array responses from backend
const normalizeArray = (data: any): any[] => {
  if (Array.isArray(data)) return data;
  if (data && Array.isArray(data.data)) return data.data;
  return [];
};

// Convert frontend status format (kebab-case) to backend format (snake_case)
const statusToBackend = (status: TaskStatus): string => {
  const statusMap: Record<TaskStatus, string> = {
    'todo': 'todo',
    'in-progress': 'in_progress',
    'review': 'in_review',
    'completed': 'completed'
  };
  return statusMap[status] || status;
};

// Convert backend status format (snake_case) to frontend format (kebab-case)
const statusToFrontend = (status: string): TaskStatus => {
  const statusMap: Record<string, TaskStatus> = {
    'todo': 'todo',
    'in_progress': 'in-progress',
    'in_review': 'review',
    'completed': 'completed'
  };
  return (statusMap[status] || status) as TaskStatus;
};

// Normalize a single task from backend format to frontend format
const normalizeTask = (task: any): Task => {
  return {
    ...task,
    id: String(task.id),
    status: statusToFrontend(task.status),
    projectId: String(task.project_id || task.projectId),
    assigneeId: task.assignee_id || task.assigneeId,
    dueDate: task.due_date || task.dueDate,
    createdAt: task.created_at || task.createdAt,
    stageTriggered: task.stage_triggered || task.stageTriggered,
  };
};

// Normalize task array
const normalizeTasks = (tasks: any[]): Task[] => {
  return tasks.map(normalizeTask);
};

export const tasksService = {
  // Get all tasks (optionally filtered by project)
  getAll: async (filters?: TaskFilters): Promise<Task[]> => {
    const response = await api.get('/api/tasks', { params: filters });
    const tasks = normalizeArray(response.data);
    return normalizeTasks(tasks);
  },

  // Get tasks for a specific project
  getByProject: async (projectId: string): Promise<Task[]> => {
    const response = await api.get(`/api/projects/${projectId}/tasks`);
    const tasks = normalizeArray(response.data);
    return normalizeTasks(tasks);
  },

  // Get single task by ID
  getById: async (id: string): Promise<Task> => {
    const response = await api.get(`/api/tasks/${id}`);
    return normalizeTask(response.data);
  },

  // Create new task
  create: async (data: CreateTaskData): Promise<Task> => {
    // Convert status to backend format before sending
    const backendData = {
      ...data,
      status: data.status ? statusToBackend(data.status) : undefined,
    };
    const response = await api.post('/api/tasks', backendData);
    const createdTask = normalizeTask(response.data);
    
    // Send notification if task is assigned to someone
    if (createdTask.assigneeId) {
      await notifyAssignment({
        type: 'task_assigned',
        userId: createdTask.assigneeId,
        taskId: createdTask.id,
        taskTitle: createdTask.title,
        projectId: createdTask.projectId,
        projectName: 'Project', // Will be fetched if needed
        dueDate: createdTask.dueDate,
        message: `You have been assigned to task "${createdTask.title}"`,
      });
    }
    
    return createdTask;
  },

  // Update task
  update: async (id: string, data: UpdateTaskData, originalTask?: Task): Promise<Task> => {
    // Convert status to backend format before sending
    const backendData = {
      ...data,
      status: data.status ? statusToBackend(data.status) : undefined,
    };
    const response = await api.put(`/api/tasks/${id}`, backendData);
    const updatedTask = normalizeTask(response.data);
    
    // Send notification if assignee changed
    if (data.assigneeId && data.assigneeId !== originalTask?.assigneeId) {
      await notifyAssignment({
        type: 'task_assigned',
        userId: data.assigneeId,
        taskId: id,
        taskTitle: data.title || originalTask?.title || 'Untitled Task',
        projectId: originalTask?.projectId || '',
        projectName: 'Project', // Will be fetched if needed
        dueDate: data.dueDate || originalTask?.dueDate,
        message: `You have been assigned to task "${data.title || originalTask?.title || 'Untitled Task'}"`,
      });
    }
    
    return updatedTask;
  },

  // Update task status only
  updateStatus: async (id: string, status: TaskStatus): Promise<Task> => {
    // Convert status to backend format
    const backendStatus = statusToBackend(status);
    const response = await api.patch(`/api/tasks/${id}/status`, { status: backendStatus });
    return normalizeTask(response.data);
  },

  // Delete task
  delete: async (id: string): Promise<void> => {
    await api.delete(`/api/tasks/${id}`);
  },

  // Assign task to user
  assign: async (id: string, assigneeId: string, originalTask?: Task): Promise<Task> => {
    const response = await api.patch(`/api/tasks/${id}/assign`, { assigneeId });
    const assignedTask = normalizeTask(response.data);
    
    // Send notification
    if (assigneeId && assigneeId !== originalTask?.assigneeId) {
      await notifyAssignment({
        type: 'task_assigned',
        userId: assigneeId,
        taskId: id,
        taskTitle: assignedTask.title,
        projectId: assignedTask.projectId,
        projectName: 'Project',
        dueDate: assignedTask.dueDate,
        message: `You have been assigned to task "${assignedTask.title}"`,
      });
    }
    
    return assignedTask;
  },
};
