export type Sector = 'Manufacturing' | 'Energy' | 'Oil and Gas' | 'Commodity Trading';

export type TaskStatus = 'todo' | 'in-progress' | 'review' | 'completed';
export type TaskPriority = 'low' | 'medium' | 'high' | 'urgent';
export type TeamRole = 'admin' | 'editor' | 'viewer';
export type RiskLevel = 'low' | 'medium' | 'high' | 'critical';

// Pipeline stages for deal progression
export type PipelineStage = 
  | 'initiation' 
  | 'qualification' 
  | 'proposal' 
  | 'negotiation' 
  | 'approval' 
  | 'execution'
  | 'closure';

export const PIPELINE_STAGES: { value: PipelineStage; label: string; order: number }[] = [
  { value: 'initiation', label: 'Initiation', order: 1 },
  { value: 'qualification', label: 'Qualification', order: 2 },
  { value: 'proposal', label: 'Proposal', order: 3 },
  { value: 'negotiation', label: 'Negotiation', order: 4 },
  { value: 'approval', label: 'Won', order: 5 },
  { value: 'execution', label: 'Execution', order: 6 },
  { value: 'closure', label: 'Closure', order: 7 },
];

export type BusinessSegment = 
  | 'EMR_MFG' 
  | 'EMR_OGP' 
  | 'EMR_Renewables' 
  | 'EMR_Trading';

export type DocumentType = 'rfq' | 'proposal' | 'contract' | 'supporting';

export interface ProjectDocument {
  id: string;
  name: string;
  type: DocumentType;
  url: string;
  uploadedAt: string;
  uploadedBy: string;
  size: number;
  source: 'local' | 'onedrive';
}

export interface TeamMember {
  id: string;
  name: string;
  email: string;
  role: TeamRole;
  avatar?: string;
  department: string;
  assignedProjects: string[];
  createdAt: string;
}

export interface Task {
  id: string;
  title: string;
  description?: string;
  status: TaskStatus;
  priority: TaskPriority;
  assigneeId?: string;
  assignee?: string;
  dueDate?: string;
  projectId: string;
  createdAt: string;
  documents?: ProjectDocument[];
  isAutoGenerated?: boolean;
  stageTriggered?: PipelineStage;
  notes?: string;
}

export interface Milestone {
  id: string;
  title: string;
  dueDate: string;
  completed: boolean;
}

export interface StageHistory {
  stage: PipelineStage;
  enteredAt: string;
  exitedAt?: string;
}

export interface Project {
  id: string;
  name: string;
  description: string;
  sector: Sector;
  status: 'active' | 'on-hold' | 'completed';
  progress: number;
  startDate: string;
  endDate?: string;
  teamSize: number;
  tasks: Task[];
  budget?: number;
  spentBudget?: number;
  riskLevel?: RiskLevel;
  clientName?: string;
  clientContact?: string;
  milestones?: Milestone[];
  documents?: ProjectDocument[];
  
  // Pipeline fields
  pipelineStage: PipelineStage;
  stageHistory?: StageHistory[];
  lastStageUpdate?: string;
  
  // Extended project fields
  pipelineIntakeDate?: string;
  oem?: string;
  location?: string;
  expectedCloseDate?: string;
  businessSegment?: BusinessSegment;
  product?: string;
  subProduct?: string;
  projectLeadId?: string;
  assigneeId?: string;
  channelPartner?: string;
  
  // Financial fields (dual currency)
  contractValueNGN?: number;
  contractValueUSD?: number;
  marginPercentNGN?: number;
  marginPercentUSD?: number;
  marginValueNGN?: number;
  marginValueUSD?: number;
  
  projectLeadComments?: string;
}

export interface DashboardStats {
  totalProjects: number;
  activeProjects: number;
  completedTasks: number;
  pendingTasks: number;
  overdueTasks: number;
}

// Integration types
export interface IntegrationConfig {
  oneDrive: {
    connected: boolean;
    lastSync?: string;
  };
  outlook: {
    connected: boolean;
    emailNotifications: boolean;
  };
}
