export type Sector = 'EMR_OGP' | 'EMR_MFG' | 'EMR_Services' | 'BEDS_Services' | 'EMR_Healthcare' | 'EMR_Renewables' | 'EMR_Trading';

export type TaskStatus = 'todo' | 'in-progress' | 'review' | 'completed';
export type TaskPriority = 'low' | 'medium' | 'high' | 'urgent';
export type TeamRole = 'admin' | 'editor' | 'viewer';
export type RiskLevel = 'low' | 'medium' | 'high' | 'critical' | 'uncertain';
export type DealProbability = 'low' | 'medium' | 'high' | 'critical' | 'uncertain';

// Pipeline stages for deal progression
export type PipelineStage = 
  | 'cold'
  | 'initiation' 
  | 'opportunity'
  | 'qualification' 
  | 'proposal' 
  | 'negotiation' 
  | 'approval' 
  | 'execution'
  | 'closure'
  | 'lost';

export const PIPELINE_STAGES: { value: PipelineStage; label: string; order: number }[] = [
  { value: 'cold', label: 'Cold', order: 0 },
  { value: 'initiation', label: 'Initiation', order: 1 },
  { value: 'opportunity', label: 'Opportunity', order: 2 },
  { value: 'qualification', label: 'Qualification', order: 3 },
  { value: 'proposal', label: 'Proposal', order: 4 },
  { value: 'negotiation', label: 'Negotiation', order: 5 },
  { value: 'approval', label: 'Approval / Won', order: 6 },
  { value: 'execution', label: 'Execution', order: 7 },
  { value: 'closure', label: 'Closure', order: 8 },
  { value: 'lost', label: 'Lost', order: 9 },
];

export type BusinessSegment = 
  | 'EMR_MFG'
  | 'EMR_OGP'
  | 'EMR_Renewables'
  | 'BEDS_Services'
  | 'EMR_Services'
  | 'EMR_Healthcare'
  | 'EMR_Trading';

export type DocumentType = 'rfq' | 'proposal' | 'contract' | 'supporting';

export interface ProjectDocument {
  id: string;
  name: string;
  type: DocumentType;
  url: string;
  uploadedAt: string;
  uploadedBy: string;
  size: number;
  source: 'local' | 'onedrive';
}

export interface TeamMember {
  id: string;
  name: string;
  email: string;
  role: TeamRole;
  avatar?: string;
  department: string;
  assignedProjects: string[];
  createdAt: string;
}

export interface Task {
  id: string;
  title: string;
  description?: string;
  status: TaskStatus;
  priority: TaskPriority;
  assigneeId?: string;
  assignee?: string;
  dueDate?: string;
  projectId: string;
  createdAt: string;
  documents?: ProjectDocument[];
  isAutoGenerated?: boolean;
  stageTriggered?: PipelineStage;
  notes?: string;
}

export interface Milestone {
  id: string;
  title: string;
  dueDate: string;
  completed: boolean;
}

export interface StageHistory {
  stage: PipelineStage;
  enteredAt: string;
  exitedAt?: string;
}

export interface Project {
  id: string;
  name: string;
  description: string;
  sector: Sector;
  status: 'active' | 'on-hold' | 'completed';
  progress: number;
  startDate: string;
  endDate?: string;
  teamSize: number;
  tasks: Task[];
  budget?: number;
  spentBudget?: number;
  dealProbability?: RiskLevel;
  clientName?: string;
  clientContact?: string;
  milestones?: Milestone[];
  documents?: ProjectDocument[];
  
  // Pipeline fields
  pipelineStage: PipelineStage;
  stageHistory?: StageHistory[];
  lastStageUpdate?: string;
  
  // Extended project fields
  pipelineIntakeDate?: string;
  oem?: string;
  location?: string;
  expectedCloseDate?: string;
  businessSegment?: BusinessSegment;
  product?: string;
  subProduct?: string;
  projectLeadId?: string;
  assigneeId?: string;
  salesLead?: string;
  channelPartner?: string;
  
  // Financial fields (dual currency)
  contractValueNGN?: number;
  contractValueUSD?: number;
  marginPercentNGN?: number;
  marginPercentUSD?: number;
  marginValueNGN?: number;
  marginValueUSD?: number;
  
  projectLeadComments?: string;
}

export interface ProjectStats {
  // Primary Statistics
  total: number;
  totalProjects: number; // Alias for 'total' (backward compatibility)
  active: number;
  activeProjects: number; // Alias for 'active'
  completed: number;
  completedProjects: number; // Alias for 'completed'
  highRisk: number;
  
  // Task Statistics
  completedTasks: number;
  pendingTasks: number;
  overdueTasks: number;
  
  // Financial Statistics
  totalValueNgn: number;
  totalValueUsd: number;
  
  // Project Metrics
  averageProgress: number;
  
  // Breakdown Statistics
  byStatus: {
    active: number;
    on_hold: number;
    completed: number;
    cancelled: number;
  };
  
  byStage: {
    [stageName: string]: number;
  };
  
  byAssignee: Array<{
    assignee: {
      id: number;
      name: string;
      email: string;
    } | null;
    count: number;
  }>;
  
  // Recent Projects
  recent: Project[];
}

// Backward compatibility alias
export interface DashboardStats extends ProjectStats {}

// Integration types
export interface IntegrationConfig {
  oneDrive: {
    connected: boolean;
    lastSync?: string;
  };
  outlook: {
    connected: boolean;
    emailNotifications: boolean;
  };
}
